name: 'bluesky-send-post'
description: 'Send posts to Bluesky from GitHub Actions'
author: 'cbrgm'

inputs:
  pds-url:
    description: 'Bluesky PDS URL'
    default: "https://bsky.social"
    required: false
  handle:
    description: 'User handle for authentication with Bluesky'
    required: true
  password:
    description: 'Password for authentication with Bluesky'
    required: true
  text:
    description: 'The content of the post'
    required: true
  lang:
    description: 'Comma-separated list of ISO 639 language codes for the post'
    default: "en"
    required: false
  log-level:
    description: 'Logging level (debug, info, warn, error)'
    required: false
    default: 'info'
  enable-embeds:
    description: 'Enable rich link card embeds for URLs in posts'
    required: false
    default: 'true'
  image-paths:
    description: 'Comma-separated list of image file paths to attach to the post (max 4 images, max 1MB each)'
    required: false
  image-alt-texts:
    description: 'Comma-separated list of alt text descriptions for images. If only one value is provided, it will be used for all images.'
    required: false
  video-path:
    description: 'Video file path to attach to the post (MP4, MOV, WebM supported, max 50MB)'
    required: false
  video-alt-text:
    description: 'Alt text description for the video'
    required: false

outputs:
  success:
    description: 'Boolean indicating if the post was successfully sent'

runs:
  using: 'docker'
  image: 'docker://ghcr.io/cbrgm/bluesky-github-action:v1'
  args:
    - --pds-url
    - ${{ inputs.pds-url }}
    - --handle
    - ${{ inputs.handle }}
    - --password
    - ${{ inputs.password }}
    - --text
    - ${{ inputs.text }}
    - --lang
    - ${{ inputs.lang }}
    - --log-level
    - ${{ inputs.log-level }}
    - --enable-embeds=${{ inputs.enable-embeds }}
    - --image-paths
    - ${{ inputs.image-paths }}
    - --image-alt-texts
    - ${{ inputs.image-alt-texts }}
    - --video-path
    - ${{ inputs.video-path }}
    - --video-alt-text
    - ${{ inputs.video-alt-text }}

branding:
  icon: send
  color: blue

