FROM i386/alpine:3.19 AS build
RUN apk add --no-cache ca-certificates

FROM scratch

ENTRYPOINT ["/usr/bin/bluesky-github-action"]

COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY bin/bluesky-github-action /usr/bin/bluesky-github-action
