name: Send Bluesky Post

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Send post to Bluesky
      id: bluesky_post
      uses: cbrgm/bluesky-github-action@02e3aa5bdb6f1ca1a71c6d40250f71ed2a65eae3 # v1.2.3
      with:
        handle: ${{ secrets.BLUESKY_HANDLE }}
        password: ${{ secrets.BLUESKY_PASSWORD }}
        text: "Hello from GitHub Actions! https://github.com/cbrgm/bluesky-github-action"

